### PR TITLE
Add shuffle button to player and update package.json to 1.1.2

### PR DESCRIPTION
**Pull request by Sonicedc**
- Changed the names of the buttons in the interaction to better match their functionality.
- Changed the player to add a shuffle button.  
- Updated version to 1.1.2 to match changes

image

### CODE REVIEW

**Comment by LewdHuTao** [comment]
Everything is looking good, and adding a new guide is a good idea but fyi this repo is fully maintained by me and i really appreciate it if you can edit the guide as this repo is not part of SudhanPlayz and wtfnotavailable organisation.

**Comment by LewdHuTao** [comment]
The code is looking code but i need to test it first before i can merge.

**Comment by Sonicedc** [comment]
> Everything is looking good, and adding a new guide is a good idea but fyi this repo is fully maintained by me and i really appreciate it if you can edit the guide as this repo is not part of SudhanPlayz and wtfnotavailable organisation.

I understand. I thought I had saw in the past that this was forked from their original repo which is why I added it. I corrected it in my guide. I will see if it can be exported to .md to make it easier on GitHub viewers and pr to your repo.

**Review by LewdHuTao — CHANGES_REQUESTED** [review]
"For live support, visit the Support channel and start a thread on [Discord](https://discord.gg/sbySMS7m3v)." 

I appreciate if you can change this part as the link is for SudhanPlayz support server. I don't have support server but if there is any questions you can directly create a new issues on this repo

**Comment by LewdHuTao** [comment]
I remove loop button interaction id on `TrackStartEvent.js` file as this PR only add shuffle button to trackStart message

**Comment by Sonicedc** [comment]
I have made the changes to the guide.  It now states that they should open an issue on the repo if they need support.
image

**Review by LewdHuTao — APPROVED** [review]

**Pull request merged**
